name: Security News
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2759341
title: Information Security News
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.00370953
  lightness: 0.6415653
  saturation: 0.9999835
  rhythmicContrast: 0.397345
purpose: []
